### ISSUE TITLE
Error Unhandled promise rejection

### ISSUE THREAD

**Issue by botmai4** [alvinmr/whatsapp-botver2#1]
`    at C:\nocache\src\index.js:22:46
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 2297)
~> [MSG] 25/10 14:22:31 Message from mai4 in group`
how to fix this?

**Comment by alvinmr** [comment]
I fixed this, you can try to pull again
